create table if not exists public.leads(id bigint generated by default as identity primary key,created_at timestamptz not null default now(),name text not null,business text,email text,phone text,service text,message text not null,source text default 'website',status text not null default 'new',notes text);
alter table public.leads enable row level security;
drop policy if exists "Public can submit leads" on public.leads;
create policy "Public can submit leads" on public.leads for insert to anon with check(true);
-- No public SELECT policy. Add Supabase Auth + admin-only RLS before exposing customer leads.
